---
name: build

on:
  push:
    branches:
    - '*'
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  build-using-nix:
    name: Build using nix environment
    runs-on: ubuntu-22.04

    steps:
      - name: git checkout
        uses: actions/checkout@v3.1.0

      - name: nix, install
        uses: DeterminateSystems/nix-installer-action@main

      - name: nix, cache
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: check code integrity
        run:  nix develop --command make check

      - name: check docs
        run:  nix develop --command make docs

      - name: check REUSE compliance
        run:  nix-shell -p reuse --run "reuse lint"

      - name: Build Release Package
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: |
          echo "Building packge"
          nix develop --command make build

      - name: Upload Release to PyPI
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: |
          echo "Uploading source code"
          nix develop --command python -m twine upload --verbose --non-interactive --skip-existing -u '__token__' -p ${{ secrets.PYPI_API_TOKEN }} dist/*